# yaml-language-server: $schema=https://raw.githubusercontent.com/serpro69/gh-arc/refs/heads/master/docs/arc.schema.json

github:
  defaultBranch: master

diff:
  requireTestPlan: false

land:
  defaultMergeMethod: rebase
